//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManavBarkod
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBManavEntities1 : DbContext
    {
        public DBManavEntities1()
            : base("name=DBManavEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLFaturaMeyve> TBLFaturaMeyve { get; set; }
        public virtual DbSet<TBLFaturaSebze> TBLFaturaSebze { get; set; }
        public virtual DbSet<TBLFatura> TBLFatura { get; set; }
        public virtual DbSet<TBLUrunler> TBLUrunler { get; set; }
        public virtual DbSet<TBLPassword> TBLPassword { get; set; }
    }
}
