//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManavBarkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFaturaMeyve
    {
        public short FaturaID { get; set; }
        public Nullable<decimal> Portakal { get; set; }
        public Nullable<decimal> Muz { get; set; }
        public Nullable<decimal> Elma { get; set; }
        public Nullable<decimal> Seftali { get; set; }
        public Nullable<decimal> Cilek { get; set; }
        public Nullable<decimal> Armut { get; set; }
        public Nullable<decimal> Karpuz { get; set; }
        public Nullable<decimal> Kiraz { get; set; }
    }
}
