//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManavBarkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFaturaSebze
    {
        public short FaturaID { get; set; }
        public Nullable<decimal> Domates { get; set; }
        public Nullable<decimal> Limon { get; set; }
        public Nullable<decimal> Salatalık { get; set; }
        public Nullable<decimal> Ispanak { get; set; }
        public Nullable<decimal> Patlıcan { get; set; }
        public Nullable<decimal> Marul { get; set; }
        public Nullable<decimal> Havuc { get; set; }
        public Nullable<decimal> YesilSogan { get; set; }
        public Nullable<decimal> Brokoli { get; set; }
        public Nullable<decimal> Sogan { get; set; }
        public Nullable<short> Maydanoz { get; set; }
    }
}
