//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManavBarkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUrunler
    {
        public short UrunID { get; set; }
        public string UrunAd { get; set; }
        public decimal UrunFiyat { get; set; }
        public string Tur { get; set; }
        public decimal Stok { get; set; }
        public decimal Maliyet { get; set; }
    }

    public class Urun
    {
        public string UrunAd { get; set; }
        public decimal UrunFiyat { get; set; }
        public decimal TopKg { get; set; }
        public decimal TopFiyat { get; set; }
        public Urun()
        {
                
        }
        public Urun(string ad, decimal fiyat , decimal topkg,decimal topfiyat)
        {
            UrunAd = ad;
            UrunFiyat = fiyat;
            this.TopKg = topkg;
            this.TopFiyat = topfiyat;
        }
    }
}
