//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUrunler
    {
        public short UrunID { get; set; }
        public string UrunAd { get; set; }
        public decimal UrunFiyat { get; set; }
        public string Tur { get; set; }
        public decimal Stok { get; set; }
        public decimal Maliyet { get; set; }

        public TBLUrunler(short urunid,string urunAd,decimal urunFiyat,string tur,decimal stok,decimal maliyet)
        {
            this.UrunID = urunid;
            this.UrunAd = urunAd;
            this.UrunFiyat = urunFiyat;
            this.Tur = tur;
            this.Stok = stok;
            this.Maliyet = maliyet;
        }
    }
}
